[package]
edition = "2018"
name = "example-rust"
version = "0.1.0"
[dependencies]
anyhow = "1.0.44"
gio = "0.14.6"
nix = "0.23"
serde_json = "1"
base64 = "0.13.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
